#!/usr/bin/env php
<?php

use Bref\Context\Context;
use Bref\Event\ApiGateway\WebsocketEvent;
use Bref\Event\ApiGateway\WebsocketHandler;
use Bref\Event\Http\HttpResponse;
use Illuminate\Contracts\Console\Kernel;

use YuK1\LaravelBrefWebsockets\Handler\HandlerSwitch;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';

} else if (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';

} else {
    require_once __DIR__ . '/../../autoload.php';
}

$app = require_once __DIR__ . '/../../../bootstrap/app.php';
$kernel = $app->make(Kernel::class);
$kernel->bootstrap();

class Handler extends WebsocketHandler
{
    public function handleWebsocket(WebsocketEvent $event, Context $context) : HttpResponse {
        return HandlerSwitch::factory($event, $context);
    }
}

return new Handler();